Vagrant.configure(2) do |config|

  # CentOS 6
  config.vm.define "el6" do |el6|
    el6.vm.box = "geerlingguy/centos6"
    el6.vm.hostname = "kibana-el6"
    el6.vm.network "forwarded_port", guest: 5601, host: 5601
    el6.vm.network "forwarded_port", guest: 9200, host: 9200
    config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 1024
      vbox.cpus = 1
    end
  end

  # CentOS 7
  config.vm.define "el7" do |el7|
    el7.vm.box = "geerlingguy/centos7"
    el7.vm.hostname = "kibana-el7"
    el7.vm.network "forwarded_port", guest: 5601, host: 5602
    el7.vm.network "forwarded_port", guest: 9200, host: 9202
    config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 1024
      vbox.cpus = 1
    end
  end

  # Ubuntu 14.04
  config.vm.define "ub14" do |ub14|
    ub14.vm.box = "geerlingguy/ubuntu1404"
    ub14.vm.hostname = "kibana-ub14"
    ub14.vm.network "forwarded_port", guest: 5601, host: 5603
    ub14.vm.network "forwarded_port", guest: 9200, host: 9203
    config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 1024
      vbox.cpus = 1
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
